name: Pixman

on:
  push:
    branches: "*"

jobs:
  build-linux-cross-container:
    name: Debian Trixie ${{ matrix.arch }}
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv6
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
            experimental: false
          - arch: armv7
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
            experimental: false
          - arch: armv7-neon
            arch_debian: armhf
            arch_gcc: arm-linux-gnueabihf
            experimental: false
          - arch: arm64
            arch_debian: arm64
            arch_gcc: aarch64-linux-gnu
            experimental: false
          - arch: power8le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
            experimental: false
          - arch: power9le
            arch_debian: ppc64el
            arch_gcc: powerpc64le-linux-gnu
            experimental: false
          - arch: s390x
            arch_debian: s390x
            arch_gcc: s390x-linux-gnu
            experimental: false

    steps:
      - run: git clone https://gitlab.freedesktop.org/pixman/pixman.git .
      - run: meson setup build --buildtype=plain -Ddefault_library=static --libdir=lib -Dtests=disabled -Ddemos=disabled -Dlibpng=disabled
      - run: meson compile -C build
      - run: meson install -C build

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: meson-log.txt
          path: build/meson-logs/meson-log.txt
